const productData = [
    {
      id: 1,
      name: "Smartwatch - Fitness Tracker",
      price: 99.99,
      image: "/public/images/Smartwatch - Fitness Tracker.jpg",
    },
    {
      id: 2,
      name: "Wireless Bluetooth Earbuds",
      price: 49.99,
      image: "/public/images/Wireless Bluetooth Earbuds.jpg",
    },
    {
      id: 3,
      name: "Laptop Backpack with USB Charging Port",
      price: 39.99,
      image: "/public/images/Laptop Backpack with USB Charging Port.jpg",
    },
    {
      id: 4,
      name: "Vintage Polaroid Camera",
      price: 79.99,
      image: "/public/images/Vintage Polaroid Camera.webp",
    },
    {
      id: 5,
      name: "Portable Espresso Maker",
      price: 69.99,
      image: "/public/images/Portable Espresso Maker.png",
    },
    {
      id: 6,
      name: "LED Desk Lamp with Wireless Charger",
      price: 34.99,
      image: "/public/images/LED Desk Lamp with Wireless Charger.jpg",
    },
    {
      id: 7,
      name: "Outdoor Waterproof Bluetooth Speaker",
      price: 89.99,
      image: "/public/images/Outdoor Waterproof Bluetooth Speaker.jpg",
    },
    {
      id: 8,
      name: "Electric Toothbrush with UV Sanitizer",
      price: 54.99,
      image: "/public/images/Electric Toothbrush with UV Sanitizer.jpg",
    },
    {
      id: 9,
      name: "Mini Projector for Home Theater",
      price: 129.99,
      image: "/public/images/Mini Projector for Home Theater.jpg",
    },
    {
      id: 10,
      name: "Professional Chef's Knife Set",
      price: 79.99,
      image: "/public/images/Professional Chef's Knife Set.jpg",
    },
    {
      id: 11,
      name: "Smart Thermostat with Voice Control",
      price: 119.99,
      image: "/public/images/Smart Thermostat with Voice Control.png",
    },
    {
      id: 12,
      name: "Reusable Stainless Steel Water Bottle",
      price: 19.99,
      image: "/public/images/Reusable Stainless Steel Water Bottle.png",
    },
    {
      id: 13,
      name: "Adjustable Dumbbell Set",
      price: 149.99,
      image: "/public/images/Adjustable Dumbbell Set.jpg",
    },
    {
      id: 14,
      name: "Indoor Plants Assortment",
      price: 29.99,
      image: "/public/images/Indoor Plants Assortment.webp",
    },
    {
      id: 15,
      name: "Robot Vacuum Cleaner with Mapping Technology",
      price: 249.99,
      image: "/public/images/Robot Vacuum Cleaner with Mapping Technology.png",
    },
    {
      id: 16,
      name: "Yoga Mat with Alignment Lines",
      price: 24.99,
      image: "/public/images/",
    },
    {
      id: 17,
      name: "Digital Drawing Tablet with Stylus",
      price: 129.99,
      image: "/public/images/Digital Air Fryer.jpeg",
    },
    {
      id: 18,
      name: "Noise-Canceling Over-Ear Headphones",
      price: 149.99,
      image: "/public/images/Noise-Canceling Over-Ear Headphones.webp",
    },
    {
      id: 19,
      name: "Instant Pot - Multi-Function Cooker",
      price: 79.99,
      image: "/public/images/Instant Pot - Multi-Function Cooker.webp",
    },
    {
      id: 20,
      name: "Virtual Reality Headset",
      price: 199.99,
      image: "/public/images/Virtual Reality Headset.jpg",
    },
    {
      id: 21,
      name: "Gaming Mechanical Keyboard",
      price: 69.99,
      image: "/public/images/Gaming Mechanical Keyboard.jpg",
    },
    {
      id: 22,
      name: "Solar-Powered Outdoor Lights",
      price: 39.99,
      image: "/public/images/Solar-Powered Outdoor Lights.jpg",
    },
    {
      id: 23,
      name: "Wall-Mounted Floating Shelves",
      price: 29.99,
      image: "/public/images/Wall-Mounted Floating Shelves.jpg",
    },
    {
      id: 24,
      name: "Compact Air Purifier",
      price: 89.99,
      image: "/public/images/Compact Air Purifier.jpg",
    },
    {
      id: 25,
      name: "Foldable Electric Scooter",
      price: 199.99,
      image: "/public/images/Foldable Electric Scooter.jpg",
    },
    {
      id: 26,
      name: "Wireless Charging Pad",
      price: 19.99,
      image: "/public/images/Wireless Charging Pad.jpg",
    },
    {
      id: 27,
      name: "Home Security Camera System",
      price: 129.99,
      image: "/public/images/Home Security Camera System.jpeg",
    },
    {
      id: 28,
      name: "Adjustable Height Standing Desk",
      price: 159.99,
      image: "/public/images/Adjustable Height Standing Desk.jpeg",
    },
    {
      id: 29,
      name: "Electric Wine Opener",
      price: 29.99,
      image: "/public/images/Electric Wine Opener.jpg",
    },
    {
      id: 30,
      name: "Resistance Band Set for Home Workouts",
      price: 14.99,
      image: "/public/images/Resistance Band Set for Home Workouts.jpeg",
    },
    {
      id: 31,
      name: "Travel-friendly Neck Pillow",
      price: 19.99,
      image: "/public/images/Travel-friendly Neck Pillow.jpg",
    },
    {
      id: 32,
      name: "Smart Home Doorbell Camera",
      price: 129.99,
      image: "/public/images/Smart Home Doorbell Camera.jpg"
    },
    {
      id: 33,
      name: "Digital Air Fryer",
      price: 89.99,
      image: "/public/images/Digital Air Fryer.jpeg",
    },
    {
      id: 34,
      name: "Ergonomic Office Chair",
      price: 129.99,
      image: "/public/images/Ergonomic Office Chair.jpeg",
    },
    {
      id: 35,
      name: "Organic Bamboo Bed Sheets",
      price: 49.99,
      image: "/public/images/Organic Bamboo Bed Sheets.jpeg",
    },
    {
      id: 36,
      name: "Portable Ice Maker",
      price: 79.99,
      image: "/public/images/Portable Ice Maker.jpeg",
    },
    {
      id: 37,
      name: "Himalayan Salt Lamp",
      price: 19.99,
      image: "/public/images/Himalayan Salt Lamp.jpeg",
    },
    {
      id: 38,
      name: "Home Exercise Bike",
      price: 249.99,
      image: "/public/images/Home Exercise Bike.jpg",
    },
    {
      id: 39,
      name: "Biodegradable Phone Case",
      price: 14.99,
      image: "/public/images/Biodegradable Phone Case.jpeg",
    },
    {
      id: 40,
      name: "Collapsible Silicone Food Containers",
      price: 29.99,
      image: "/public/images/Collapsible Silicone Food Container.jpg",
    },
    {
      id: 41,
      name: "Bluetooth Keyboard for Tablets",
      price: 39.99,
      image: "/public/images/Bluetooth Keyboard for Tablets.jpg",
    },
    {
      id: 42,
      name: "Personalized Name Necklace",
      price: 49.99,
      image: "/public/images/Personalized Name Necklace.jpg",
    },
    {
      id: 43,
      name: "Aromatherapy Essential Oil Diffuser",
      price: 34.99,
      image: "/public/images/Aromatherapy Essential Oil Diffuser.jpg",
    },
    {
      id: 44,
      name: "Wireless Charging Mouse Pad",
      price: 24.99,
      image: "/public/images/Wireless Charging Mouse Pad.jpeg",
    },
    {
      id: 45,
      name: "WiFi Range Extender",
      price: 29.99,
      image: "/public/images/WiFi Range Extender.webp",
    },
    {
      id: 46,
      name: "Handheld Milk Frother",
      price: 14.99,
      image: "/public/images/Handheld Milk Frother.jpg",
    },
    {
      id: 47,
      name: "Insulated Stainless Steel Lunch Box",
      price: 19.99,
      image: "/public/images/Insulated Stainless Steel Lunch Box.jpg",
    },
    {
      id: 48,
      name: "Minimalist Leather Wallet",
      price: 39.99,
      image: "/public/images/Minimalist Leather Wallet.jpeg",
    },
    {
      id: 49,
      name: "Portable UV-C Sanitizer Wand",
      price: 49.99,
      image: "/public/images/Portable UV-C Sanitizer Wand.jpg",
    },
    {
      id: 50,
      name: "Customizable LED Light Strips",
      price: 29.99,
      image: "/public/images/Customizable LED Light Strips.webp",
    },
    {
      id: 51,
      name: "Smart Refrigerator with Touchscreen",
      price: 1499.99,
      image: "/public/images/Smart Refrigerator with Touchscreen.jpg",
    },
    {
      id: 52,
      name: "Wireless Charging Desk Organizer",
      price: 49.99,
      image: "/public/images/Wireless Charging Desk Organizer.jpeg",
    },
    {
      id: 53,
      name: "Bluetooth Smart Scale",
      price: 34.99,
      image: "/public/images/Bluetooth Smart Scale.webp",
    },
    {
      id: 54,
      name: "Fitness Tracker Smart Ring",
      price: 79.99,
      image: "/public/images/Fitness Tracker Smart Ring.jpeg",
    },
    {
      id: 55,
      name: "Cordless Handheld Vacuum Cleaner",
      price: 129.99,
      image: "/public/images/Cordless Handheld Vacuum Cleaner.jpg",
    },
    {
      id: 56,
      name: "Electric Heating Pad",
      price: 24.99,
      image: "/public/images/Electric Heating Pad.jpeg",
    },
    {
      id: 57,
      name: "Folding Electric Bike",
      price: 499.99,
      image: "/public/images/Folding Electric Bike.webp",
    },
    {
      id: 58,
      name: "Smart Mirror with AI Technology",
      price: 299.99,
      image: "/public/images/Smart Mirror with AI Technology.webp",
    },
    {
      id: 59,
      name: "Outdoor Camping Hammock",
      price: 39.99,
      image: "/public/images/Outdoor Camping Hammock.jpeg",
    },
    {
      id: 60,
      name: "Wireless Car Charger Mount",
      price: 44.99,
      image: "/public/images/Wireless Car Charger Mount.jpeg",
    },
    {
      id: 61,
      name: "Solar-Powered Phone Charger",
      price: 19.99,
      image: "/public/images/Solar-Powered Phone Charger.jpeg",
    },
    {
      id: 62,
      name: "Smart Water Bottle with Hydration Reminder",
      price: 29.99,
      image: "/public/images/Smart Water Bottle with Hydration Reminder.jpeg",
    },
    {
      id: 63,
      name: "Gourmet Coffee Beans Set",
      price: 19.99,
      image: "/public/images/Gourmet Coffee Beans Set.jpg",
    },
    {
      id: 64,
      name: "Digital Meat Thermometer",
      price: 14.99,
      image: "/public/images/Digital Meat Thermometer.jpeg",
    },
    {
      id: 65,
      name: "Portable Bluetooth Karaoke Microphone",
      price: 39.99,
      image: "/public/images/Portable Bluetooth Karaoke Microphone.jpg",
    },
    {
      id: 66,
      name: "Smart Wi-Fi Sprinkler Controller",
      price: 89.99,
      image: "/public/images/Smart Wi-Fi Sprinkler Controller.jpg",
    },
    {
      id: 67,
      name: "Mini Air Humidifier",
      price: 24.99,
      image: "/public/images/Mini Air Humidifier.jpeg",
    },
    {
      id: 68,
      name: "Adjustable Laptop Stand",
      price: 29.99,
      image: "/public/images/Adjustable Laptop Stand.png",
    },
    {
      id: 69,
      name: "Wireless Noise-Canceling Sleep Mask",
      price: 49.99,
      image: "/public/images/Wireless Noise-Canceling Sleep Mask.jpeg",
    },
    {
      id: 70,
      name: "UV-C Light Sanitizing Wand",
      price: 34.99,
      image: "/public/images/UV-C Light Sanitizing Wand.jpeg",
    },
  ];
  
  export default productData;
  